name: Download and CN LIST

on:
  schedule:
    - cron: '0 0 * * 6'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  process-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许推送更改

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3

      - name: 下载 Global_Compilation.txt
        run: |
          curl -L -o Global_Compilation.txt "https://raw.githubusercontent.com/cs2021hv001/Global_Compilation/refs/heads/main/cn_urls.txt"

      - name: 读取链接并下载文件
        run: |
          mkdir -p downloaded_files
          mkdir -p logs
          failed_count=0
          failed_log="logs/CN_downloads.log"
          echo "===== 下载失败日志 =====" > "$failed_log"
          echo "时间: $(date)" >> "$failed_log"
          
          while IFS= read -r url; do
            if [ -n "$url" ]; then
              if ! curl -L --retry 3 --max-time 10 "$url" >> downloaded_files/merged.txt; then
                echo "$url" >> "$failed_log"
                ((failed_count++))
              else
                echo "" >> downloaded_files/merged.txt
              fi
            fi
          done < Global_Compilation.txt
          
          echo "下载失败的总数: $failed_count" >> "$failed_log"
          touch "$failed_log"

      - name: 下载并合并 gfw.txt
        run: |
          mkdir -p output
          
          # 处理 merged.txt，去掉 DOMAIN-SUFFIX, 前缀
          grep '^DOMAIN-SUFFIX,' downloaded_files/merged.txt | sed 's/^DOMAIN-SUFFIX,//' > output/temp_list.txt
          
          # 下载 gfw.txt 并追加
          curl -L -o downloaded_files/gfw.txt "https://fastly.jsdelivr.net/gh/felixonmars/dnsmasq-china-list/accelerated-domains.china.conf"
          cat downloaded_files/gfw.txt >> output/temp_list.txt

          # 提取域名、初步去重
          sed -e 's/^server=\/\([^\/]*\)\/114\.114\.114\.114/\1/' output/temp_list.txt | sort -u > output/CN_LIST.conf
          rm output/temp_list.txt

          # 再次确认去重（防止意外重复）
          sort -u output/CN_LIST.conf -o output/CN_LIST.conf
 
          # 提交更改
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          # 强制更新文件时间戳，确保每次运行都提交
          touch output/CN_LIST.conf logs/CN_downloads.log
          git add output/CN_LIST.conf logs/CN_downloads.log
          git commit -m "Update CN_LIST.conf and CN_downloads.log for run at $(date -u)" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
